/**
 * Demonstration data set.
 *
 * Everything here is illustrative and invented: the people, the agencies, the
 * contract references and the numbers. It is framed around an AUT Strategy and
 * Transformation portfolio because that is the context the app was built for,
 * but no real supplier relationship, individual or commercial term is implied.
 * Settings gives you a one-click reset to an empty register.
 */

import { addDays, toISO, today } from "./calc";
import {
  AppData,
  Approval,
  ChecklistItem,
  Contractor,
  DEFAULT_SETTINGS,
  Invoice,
  Project,
  RateCardEntry,
  Variation,
  Vendor,
} from "./types";

const d = (offsetDays: number) => toISO(addDays(today(), offsetDays));

const ONBOARD_TEMPLATE = (start: string): ChecklistItem[] => [
  { task: "Contract signed and countersigned", done: true, dueDate: start, owner: "Procurement" },
  { task: "Purchase order raised", done: true, dueDate: start, owner: "Finance" },
  { task: "Background check cleared", done: true, dueDate: start, owner: "People and Culture" },
  { task: "Network account and MFA", done: true, dueDate: start, owner: "Service Desk" },
  { task: "Laptop and campus card issued", done: true, dueDate: start, owner: "Service Desk" },
  { task: "Induction and health and safety briefing", done: true, dueDate: start, owner: "Hiring manager" },
];

const OFFBOARD_TEMPLATE = (end: string): ChecklistItem[] => [
  { task: "Knowledge handover documented", done: false, dueDate: end, owner: "Hiring manager" },
  { task: "Accounts disabled", done: false, dueDate: end, owner: "Service Desk" },
  { task: "Privileged access revoked", done: false, dueDate: end, owner: "Cyber Security" },
  { task: "Equipment and campus card returned", done: false, dueDate: end, owner: "Service Desk" },
  { task: "Final invoice reconciled to PO", done: false, dueDate: end, owner: "Finance" },
];

export function seedData(): AppData {
  const vendors: Vendor[] = [
    {
      id: "ven_harbourline",
      name: "Harbourline Talent",
      type: "agency",
      accountManagerName: "Karen Whitfield",
      accountManagerEmail: "karen.whitfield@harbourline.example",
      accountManagerPhone: "+64 9 555 0142",
      msaRef: "MSA-2024-011",
      msaExpiry: d(75),
      marginPct: 14,
      paymentTermsDays: 30,
      piInsuranceExpiry: d(180),
      plInsuranceExpiry: d(180),
      active: true,
      notes:
        "Primary infrastructure and service desk supplier. Rate card reviewed each March. Reliable on submissions, slow on paperwork.",
    },
    {
      id: "ven_kauri",
      name: "Kauri Digital Partners",
      type: "agency",
      accountManagerName: "Sione Faleolo",
      accountManagerEmail: "sione.faleolo@kauridigital.example",
      accountManagerPhone: "+64 9 555 0188",
      msaRef: "MSA-2025-004",
      msaExpiry: d(310),
      marginPct: 16,
      paymentTermsDays: 30,
      piInsuranceExpiry: d(-4),
      plInsuranceExpiry: d(95),
      active: true,
      notes:
        "Data and analytics bench. PI certificate has lapsed and has been chased twice without a reply.",
    },
    {
      id: "ven_ravensbourne",
      name: "Ravensbourne Technology",
      type: "consultancy",
      accountManagerName: "Priya Nair",
      accountManagerEmail: "priya.nair@ravensbourne.example",
      accountManagerPhone: "+64 9 555 0233",
      msaRef: "MSA-2023-027",
      msaExpiry: d(25),
      marginPct: null,
      paymentTermsDays: 45,
      piInsuranceExpiry: d(240),
      plInsuranceExpiry: d(240),
      active: true,
      notes:
        "Statement-of-work based, so watch deliverables rather than dates. Invoices monthly in arrears and always late.",
    },
    {
      id: "ven_northpoint",
      name: "Northpoint Recruitment",
      type: "agency",
      accountManagerName: "Doug McAllister",
      accountManagerEmail: "doug.mcallister@northpoint.example",
      accountManagerPhone: "+64 9 555 0311",
      msaRef: "MSA-2025-019",
      msaExpiry: d(420),
      marginPct: 18,
      paymentTermsDays: 21,
      piInsuranceExpiry: d(60),
      plInsuranceExpiry: d(60),
      active: true,
      notes:
        "Newer panel member on higher margin. Used for hard-to-fill security roles.",
    },
  ];

  const projects: Project[] = [
    { id: "prj_bau", name: "BAU / Run", code: "DIG-BAU", costCentre: "CC-4100", sponsor: "Director Digital Services", budget: 1200000, active: true },
    { id: "prj_sms", name: "Student Management System Replacement", code: "PRJ-1042", costCentre: "CC-4210", sponsor: "Deputy Vice-Chancellor Operations", budget: 2400000, active: true },
    { id: "prj_net", name: "Campus Network Refresh", code: "PRJ-1088", costCentre: "CC-4150", sponsor: "Head of Infrastructure", budget: 850000, active: true },
    { id: "prj_data", name: "Data Platform Uplift", code: "PRJ-1101", costCentre: "CC-4320", sponsor: "Head of Data and Insights", budget: 1100000, active: true },
    { id: "prj_cyber", name: "Cyber Uplift Programme", code: "PRJ-1120", costCentre: "CC-4400", sponsor: "Chief Information Security Officer", budget: 640000, active: true },
  ];

  const rateCard: RateCardEntry[] = [
    { id: "rc_001", role: "Senior Network Engineer", level: "Senior", benchmarkHourly: 112, source: "Panel rate card 2026", reviewedOn: d(-60) },
    { id: "rc_002", role: "Power BI Developer", level: "Intermediate", benchmarkHourly: 108, source: "Panel rate card 2026", reviewedOn: d(-60) },
    { id: "rc_003", role: "Security Engineer", level: "Senior", benchmarkHourly: 130, source: "Market scan Q1 2026", reviewedOn: d(-90) },
    { id: "rc_004", role: "Test Manager", level: "Lead", benchmarkHourly: 135, source: "Market scan Q1 2026", reviewedOn: d(-90) },
    { id: "rc_005", role: "Service Desk Analyst", level: "Analyst", benchmarkHourly: 58, source: "Panel rate card 2026", reviewedOn: d(-60) },
    { id: "rc_006", role: "Programme Manager", level: "Lead", benchmarkHourly: 165, source: "Market scan Q1 2026", reviewedOn: d(-90) },
    { id: "rc_007", role: "Data Engineer", level: "Intermediate", benchmarkHourly: 110, source: "Panel rate card 2026", reviewedOn: d(-60) },
    { id: "rc_008", role: "Cloud Platform Engineer", level: "Senior", benchmarkHourly: 120, source: "Panel rate card 2026", reviewedOn: d(-60) },
    { id: "rc_009", role: "Integration Developer", level: "Senior", benchmarkHourly: 118, source: "Market scan Q1 2026", reviewedOn: d(-90) },
    { id: "rc_010", role: "Identity and Access Consultant", level: "Senior", benchmarkHourly: 132, source: "Market scan Q1 2026", reviewedOn: d(-90) },
  ];

  const contractors: Contractor[] = [
    {
      id: "con_0001",
      firstName: "Michael",
      lastName: "Okafor",
      preferredName: "Mike",
      workerId: "C-10021",
      email: "mike.okafor@example.com",
      phone: "+64 21 555 011",
      dateOfBirth: "1984-03-12",
      gender: "Male",
      nationality: "New Zealand",
      workRightsType: "NZ Citizen",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "Amara Okafor", relationship: "Partner", phone: "+64 21 555 012" },
      engagementType: "intermediated",
      vendorId: "ven_harbourline",
      role: "Senior Network Engineer",
      team: "Infrastructure",
      hiringManager: "Rachel Lim",
      status: "active",
      startDate: d(-790),
      endDate: d(48),
      originalEndDate: d(-45),
      hoursPerWeek: 40,
      rateBasis: "hourly",
      chargeRate: 118,
      payRate: 101,
      contractRef: "CTR-2025-0142",
      poNumber: "PO-88213",
      poValue: 260000,
      poSpentToDate: 224000,
      extensionCount: 2,
      noticePeriodDays: 20,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "CAPEX-2025-77",
      rehireEligible: "yes",
      performanceNote: "Strong technically. Rachel rates him as the best network hire in three years.",
      allocations: [
        { projectId: "prj_net", sharePct: 70 },
        { projectId: "prj_bau", sharePct: 30 },
      ],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-792), revokedOn: "" },
        { system: "Network admin (privileged)", status: "active", requestedOn: d(-790), revokedOn: "" },
        { system: "Service management tool", status: "active", requestedOn: d(-790), revokedOn: "" },
      ],
      assets: [
        { item: "Laptop", assetTag: "AKL-LT-3391", issuedOn: d(-790), returnedOn: "" },
        { item: "Console cable kit", assetTag: "AKL-KIT-0210", issuedOn: d(-788), returnedOn: "" },
      ],
      onboarding: ONBOARD_TEMPLATE(d(-790)),
      offboarding: OFFBOARD_TEMPLATE(d(48)),
      notes:
        "Tenure is well past the review threshold. Rachel wants a permanent conversion case built before any further extension.",
    },
    {
      id: "con_0002",
      firstName: "Aroha",
      lastName: "Ngata",
      preferredName: "",
      workerId: "C-10044",
      email: "aroha.ngata@example.com",
      phone: "+64 21 555 021",
      dateOfBirth: "1991-07-28",
      gender: "Female",
      nationality: "New Zealand",
      workRightsType: "NZ Citizen",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "Tane Ngata", relationship: "Brother", phone: "+64 21 555 022" },
      engagementType: "intermediated",
      vendorId: "ven_kauri",
      role: "Power BI Developer",
      team: "Data and Insights",
      hiringManager: "Sam Devlin",
      status: "active",
      startDate: d(-160),
      endDate: d(112),
      originalEndDate: d(112),
      hoursPerWeek: 32,
      rateBasis: "daily",
      chargeRate: 920,
      payRate: 780,
      contractRef: "CTR-2026-0031",
      poNumber: "PO-90114",
      poValue: 180000,
      poSpentToDate: 74000,
      extensionCount: 0,
      noticePeriodDays: 10,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "OPEX-2026-14",
      rehireEligible: "yes",
      performanceNote: "Delivers clean semantic models. Well regarded by the finance reporting team.",
      allocations: [{ projectId: "prj_data", sharePct: 100 }],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-162), revokedOn: "" },
        { system: "Power BI workspace", status: "active", requestedOn: d(-160), revokedOn: "" },
        { system: "Azure DevOps", status: "active", requestedOn: d(-158), revokedOn: "" },
      ],
      assets: [{ item: "Laptop", assetTag: "AKL-LT-4102", issuedOn: d(-160), returnedOn: "" }],
      onboarding: ONBOARD_TEMPLATE(d(-160)),
      offboarding: OFFBOARD_TEMPLATE(d(112)),
      notes: "Four days a week, not available Fridays.",
    },
    {
      id: "con_0003",
      firstName: "Dmitri",
      lastName: "Volkov",
      preferredName: "",
      workerId: "C-10052",
      email: "dmitri.volkov@example.com",
      phone: "+64 21 555 031",
      dateOfBirth: "1988-11-04",
      gender: "Male",
      nationality: "Latvia",
      workRightsType: "Accredited Employer Work Visa",
      workRightsExpiry: d(41),
      location: "Auckland",
      emergencyContact: { name: "Elina Volkova", relationship: "Spouse", phone: "+64 21 555 032" },
      engagementType: "intermediated",
      vendorId: "ven_northpoint",
      role: "Security Engineer",
      team: "Cyber Security",
      hiringManager: "Nadia Whare",
      status: "active",
      startDate: d(-95),
      endDate: d(178),
      originalEndDate: d(178),
      hoursPerWeek: 40,
      rateBasis: "hourly",
      chargeRate: 135,
      payRate: 110,
      contractRef: "CTR-2026-0058",
      poNumber: "PO-90402",
      poValue: 300000,
      poSpentToDate: 96000,
      extensionCount: 0,
      noticePeriodDays: 20,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Elevated",
      approvalRef: "CAPEX-2026-09",
      rehireEligible: "yes",
      performanceNote: "Settled in quickly. Picked up the privileged access rollout without hand-holding.",
      allocations: [
        { projectId: "prj_cyber", sharePct: 80 },
        { projectId: "prj_bau", sharePct: 20 },
      ],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-97), revokedOn: "" },
        { system: "Security operations platform", status: "active", requestedOn: d(-95), revokedOn: "" },
        { system: "Privileged access vault", status: "active", requestedOn: d(-93), revokedOn: "" },
      ],
      assets: [
        { item: "Laptop", assetTag: "AKL-LT-4310", issuedOn: d(-95), returnedOn: "" },
        { item: "Hardware security keys x2", assetTag: "AKL-SEC-0088", issuedOn: d(-95), returnedOn: "" },
      ],
      onboarding: ONBOARD_TEMPLATE(d(-95)),
      offboarding: OFFBOARD_TEMPLATE(d(178)),
      notes:
        "Visa expiry lands well before the contract end. Renewal evidence still outstanding from Northpoint.",
    },
    {
      id: "con_0004",
      firstName: "Grace",
      lastName: "Thompson",
      preferredName: "",
      workerId: "C-10061",
      email: "grace.thompson@example.com",
      phone: "+64 21 555 041",
      dateOfBirth: "1979-01-19",
      gender: "Female",
      nationality: "United Kingdom",
      workRightsType: "NZ Resident",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "Peter Thompson", relationship: "Spouse", phone: "+64 21 555 042" },
      engagementType: "direct",
      vendorId: null,
      role: "Test Manager",
      team: "Student Systems",
      hiringManager: "Ben Osei",
      status: "active",
      startDate: d(-220),
      endDate: d(15),
      originalEndDate: d(-30),
      hoursPerWeek: 40,
      rateBasis: "daily",
      chargeRate: 1150,
      payRate: null,
      contractRef: "CTR-2025-0208",
      poNumber: "PO-89551",
      poValue: 240000,
      poSpentToDate: 214500,
      extensionCount: 1,
      noticePeriodDays: 15,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "PRJ-1042-CR-06",
      rehireEligible: "yes",
      performanceNote: "Ran the test cycle to plan. Would take back for the next release.",
      allocations: [{ projectId: "prj_sms", sharePct: 100 }],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-222), revokedOn: "" },
        { system: "SMS test environment", status: "active", requestedOn: d(-220), revokedOn: "" },
        { system: "Test management tool", status: "active", requestedOn: d(-219), revokedOn: "" },
      ],
      assets: [{ item: "Laptop", assetTag: "AKL-LT-1188", issuedOn: d(-220), returnedOn: "" }],
      onboarding: ONBOARD_TEMPLATE(d(-220)),
      offboarding: OFFBOARD_TEMPLATE(d(15)),
      notes:
        "Direct engagement, invoices monthly. The end date is already inside the notice window and no decision has been made.",
    },
    {
      id: "con_0005",
      firstName: "Ravi",
      lastName: "Subramanian",
      preferredName: "",
      workerId: "C-10070",
      email: "ravi.subramanian@example.com",
      phone: "+64 21 555 051",
      dateOfBirth: "1993-05-30",
      gender: "Male",
      nationality: "India",
      workRightsType: "Post Study Work Visa",
      workRightsExpiry: d(300),
      location: "Auckland",
      emergencyContact: { name: "Lakshmi Subramanian", relationship: "Mother", phone: "+91 98 555 0053" },
      engagementType: "intermediated",
      vendorId: "ven_harbourline",
      role: "Service Desk Analyst",
      team: "Digital Services",
      hiringManager: "Rachel Lim",
      status: "active",
      startDate: d(-70),
      endDate: d(110),
      originalEndDate: d(110),
      hoursPerWeek: 20,
      rateBasis: "hourly",
      chargeRate: 62,
      payRate: 53,
      contractRef: "CTR-2026-0071",
      poNumber: "PO-90520",
      poValue: 60000,
      poSpentToDate: 17800,
      extensionCount: 0,
      noticePeriodDays: 10,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "OPEX-2026-21",
      rehireEligible: "yes",
      performanceNote: "Reliable on the afternoon shift. Ticket quality good.",
      allocations: [{ projectId: "prj_bau", sharePct: 100 }],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-72), revokedOn: "" },
        { system: "Service management tool", status: "active", requestedOn: d(-70), revokedOn: "" },
      ],
      assets: [{ item: "Laptop", assetTag: "AKL-LT-4455", issuedOn: d(-70), returnedOn: "" }],
      onboarding: ONBOARD_TEMPLATE(d(-70)),
      offboarding: OFFBOARD_TEMPLATE(d(110)),
      notes: "Half time, covering the afternoon shift.",
    },
    {
      id: "con_0006",
      firstName: "Helen",
      lastName: "Mackenzie",
      preferredName: "",
      workerId: "C-10078",
      email: "helen.mackenzie@example.com",
      phone: "+64 21 555 061",
      dateOfBirth: "1975-09-09",
      gender: "Female",
      nationality: "New Zealand",
      workRightsType: "NZ Citizen",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "Iain Mackenzie", relationship: "Spouse", phone: "+64 21 555 062" },
      engagementType: "intermediated",
      vendorId: "ven_ravensbourne",
      role: "Programme Manager",
      team: "Portfolio Office",
      hiringManager: "Ben Osei",
      status: "active",
      startDate: d(-300),
      endDate: d(96),
      originalEndDate: d(-15),
      hoursPerWeek: 40,
      rateBasis: "daily",
      chargeRate: 1480,
      payRate: null,
      contractRef: "SOW-2025-0094",
      poNumber: "PO-89012",
      poValue: 520000,
      poSpentToDate: 401000,
      extensionCount: 1,
      noticePeriodDays: 30,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "PRJ-1042-CR-04",
      rehireEligible: "yes",
      performanceNote: "Effective but expensive. The programme would stall without her.",
      allocations: [{ projectId: "prj_sms", sharePct: 100 }],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-302), revokedOn: "" },
        { system: "Portfolio management tool", status: "active", requestedOn: d(-300), revokedOn: "" },
        { system: "Programme SharePoint", status: "active", requestedOn: d(-300), revokedOn: "" },
      ],
      assets: [{ item: "Laptop", assetTag: "AKL-LT-3902", issuedOn: d(-300), returnedOn: "" }],
      onboarding: ONBOARD_TEMPLATE(d(-300)),
      offboarding: OFFBOARD_TEMPLATE(d(96)),
      notes:
        "Highest day rate on the register and the PO is nearly gone. Statement-of-work based, so watch the deliverable schedule not just the dates.",
    },
    {
      id: "con_0007",
      firstName: "Tomas",
      lastName: "Silva",
      preferredName: "Tom",
      workerId: "C-10084",
      email: "tomas.silva@example.com",
      phone: "+64 21 555 071",
      dateOfBirth: "1996-02-14",
      gender: "Male",
      nationality: "Brazil",
      workRightsType: "Accredited Employer Work Visa",
      workRightsExpiry: d(520),
      location: "Auckland",
      emergencyContact: { name: "Beatriz Silva", relationship: "Sister", phone: "+55 11 555 0071" },
      engagementType: "intermediated",
      vendorId: "ven_kauri",
      role: "Data Engineer",
      team: "Data and Insights",
      hiringManager: "Sam Devlin",
      status: "onboarding",
      startDate: d(12),
      endDate: d(194),
      originalEndDate: d(194),
      hoursPerWeek: 40,
      rateBasis: "hourly",
      chargeRate: 112,
      payRate: 94,
      contractRef: "CTR-2026-0090",
      poNumber: "",
      poValue: 220000,
      poSpentToDate: 0,
      extensionCount: 0,
      noticePeriodDays: 20,
      statusTestCompleted: true,
      backgroundCheckCompleted: false,
      healthSafetyInducted: false,
      securityClearance: "Standard",
      approvalRef: "PRJ-1101-CR-02",
      rehireEligible: "unknown",
      performanceNote: "",
      allocations: [{ projectId: "prj_data", sharePct: 100 }],
      accounts: [
        { system: "Entra ID", status: "requested", requestedOn: d(-2), revokedOn: "" },
        { system: "Data platform", status: "not-requested", requestedOn: "", revokedOn: "" },
      ],
      assets: [],
      onboarding: [
        { task: "Contract signed and countersigned", done: true, dueDate: d(-5), owner: "Procurement" },
        { task: "Purchase order raised", done: false, dueDate: d(4), owner: "Finance" },
        { task: "Background check cleared", done: false, dueDate: d(6), owner: "People and Culture" },
        { task: "Network account and MFA", done: false, dueDate: d(10), owner: "Service Desk" },
        { task: "Laptop and campus card issued", done: false, dueDate: d(11), owner: "Service Desk" },
        { task: "Induction and health and safety briefing", done: false, dueDate: d(12), owner: "Hiring manager" },
      ],
      offboarding: OFFBOARD_TEMPLATE(d(194)),
      notes:
        "Starts in a fortnight and the PO still is not raised. The usual bottleneck.",
    },
    {
      id: "con_0008",
      firstName: "Claire",
      lastName: "Dubois",
      preferredName: "",
      workerId: "C-10011",
      email: "claire.dubois@example.com",
      phone: "+64 21 555 081",
      dateOfBirth: "1986-06-22",
      gender: "Female",
      nationality: "France",
      workRightsType: "NZ Resident",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "Marc Dubois", relationship: "Spouse", phone: "+64 21 555 082" },
      engagementType: "intermediated",
      vendorId: "ven_harbourline",
      role: "Cloud Platform Engineer",
      team: "Infrastructure",
      hiringManager: "Rachel Lim",
      status: "ended",
      startDate: d(-540),
      endDate: d(-30),
      originalEndDate: d(-30),
      hoursPerWeek: 40,
      rateBasis: "hourly",
      chargeRate: 124,
      payRate: 106,
      contractRef: "CTR-2024-0177",
      poNumber: "PO-87003",
      poValue: 340000,
      poSpentToDate: 338900,
      extensionCount: 3,
      noticePeriodDays: 20,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "CAPEX-2024-52",
      rehireEligible: "yes",
      performanceNote: "Left on good terms. Approached about a permanent role and declined.",
      allocations: [{ projectId: "prj_net", sharePct: 100 }],
      accounts: [
        { system: "Entra ID", status: "revoked", requestedOn: d(-542), revokedOn: d(-29) },
        { system: "Cloud subscription owner", status: "revoked", requestedOn: d(-540), revokedOn: d(-29) },
      ],
      assets: [{ item: "Laptop", assetTag: "AKL-LT-2901", issuedOn: d(-540), returnedOn: d(-28) }],
      onboarding: ONBOARD_TEMPLATE(d(-540)),
      offboarding: [
        { task: "Knowledge handover documented", done: true, dueDate: d(-32), owner: "Hiring manager" },
        { task: "Accounts disabled", done: true, dueDate: d(-29), owner: "Service Desk" },
        { task: "Privileged access revoked", done: true, dueDate: d(-29), owner: "Cyber Security" },
        { task: "Equipment and campus card returned", done: true, dueDate: d(-28), owner: "Service Desk" },
        { task: "Final invoice reconciled to PO", done: false, dueDate: d(-5), owner: "Finance" },
      ],
      notes: "Finished after three extensions. Final invoice is still not reconciled.",
    },
    {
      id: "con_0009",
      firstName: "Jonah",
      lastName: "Peters",
      preferredName: "",
      workerId: "",
      email: "jonah.peters@example.com",
      phone: "+64 21 555 091",
      dateOfBirth: "1990-10-02",
      gender: "Male",
      nationality: "New Zealand",
      workRightsType: "NZ Citizen",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "", relationship: "", phone: "" },
      engagementType: "intermediated",
      vendorId: "ven_northpoint",
      role: "Identity and Access Consultant",
      team: "Cyber Security",
      hiringManager: "Nadia Whare",
      status: "pipeline",
      startDate: d(38),
      endDate: d(220),
      originalEndDate: d(220),
      hoursPerWeek: 24,
      rateBasis: "hourly",
      chargeRate: 128,
      payRate: 108,
      contractRef: "",
      poNumber: "",
      poValue: null,
      poSpentToDate: 0,
      extensionCount: 0,
      noticePeriodDays: 20,
      statusTestCompleted: false,
      backgroundCheckCompleted: false,
      healthSafetyInducted: false,
      securityClearance: "Elevated",
      approvalRef: "",
      rehireEligible: "unknown",
      performanceNote: "",
      allocations: [{ projectId: "prj_cyber", sharePct: 100 }],
      accounts: [],
      assets: [],
      onboarding: [
        { task: "Rate approved by CISO", done: false, dueDate: d(10), owner: "Nadia Whare" },
        { task: "Contract issued", done: false, dueDate: d(20), owner: "Procurement" },
        { task: "Background and vetting", done: false, dueDate: d(30), owner: "People and Culture" },
      ],
      offboarding: OFFBOARD_TEMPLATE(d(220)),
      notes: "Three days a week. Not yet approved, so excluded from committed cost.",
    },
    {
      id: "con_0010",
      firstName: "Wiremu",
      lastName: "Katene",
      preferredName: "",
      workerId: "C-10090",
      email: "wiremu.katene@example.com",
      phone: "+64 21 555 101",
      dateOfBirth: "1982-12-01",
      gender: "Male",
      nationality: "New Zealand",
      workRightsType: "NZ Citizen",
      workRightsExpiry: "",
      location: "Auckland",
      emergencyContact: { name: "Mere Katene", relationship: "Spouse", phone: "+64 21 555 102" },
      engagementType: "intermediated",
      vendorId: "ven_ravensbourne",
      role: "Integration Developer",
      team: "Student Systems",
      hiringManager: "Ben Osei",
      status: "notice",
      startDate: d(-260),
      endDate: d(9),
      originalEndDate: d(9),
      hoursPerWeek: 40,
      rateBasis: "hourly",
      chargeRate: 121,
      payRate: null,
      contractRef: "SOW-2025-0111",
      poNumber: "PO-89740",
      poValue: 260000,
      poSpentToDate: 246000,
      extensionCount: 0,
      noticePeriodDays: 15,
      statusTestCompleted: true,
      backgroundCheckCompleted: true,
      healthSafetyInducted: true,
      securityClearance: "Standard",
      approvalRef: "PRJ-1042-CR-05",
      rehireEligible: "yes",
      performanceNote: "Solid delivery. Handover documentation has been thorough.",
      allocations: [
        { projectId: "prj_sms", sharePct: 60 },
        { projectId: "prj_bau", sharePct: 40 },
      ],
      accounts: [
        { system: "Entra ID", status: "active", requestedOn: d(-262), revokedOn: "" },
        { system: "Integration platform", status: "active", requestedOn: d(-260), revokedOn: "" },
      ],
      assets: [{ item: "Laptop", assetTag: "AKL-LT-3777", issuedOn: d(-260), returnedOn: "" }],
      onboarding: ONBOARD_TEMPLATE(d(-260)),
      offboarding: OFFBOARD_TEMPLATE(d(9)),
      notes: "Not extending. Handover to the permanent integration squad is in progress.",
    },
  ];

  const approvals: Approval[] = [
    {
      id: "apr_0001",
      contractorId: "con_0001",
      kind: "extension",
      reference: "CR-2026-118",
      description:
        "Three month extension to hold the network refresh through cutover. Rate held at current level.",
      value: 61360,
      raisedOn: d(-18),
      requiredBy: d(28),
      state: "with-approver",
      currentApprover: "Rachel Lim",
      currentApproverRole: "Head of Infrastructure",
      withApproverSince: d(-11),
      decidedOn: "",
      chases: [
        { date: d(-6), channel: "email", chasedWho: "Rachel Lim", note: "Asked for a decision, flagged the notice date.", outcome: "Said she would look at it this week." },
        { date: d(-2), channel: "teams", chasedWho: "Rachel Lim", note: "Second nudge with the tenure position attached.", outcome: "No response yet." },
      ],
      notes:
        "Tenure review needs to be resolved before this can be approved. Sitting behind that.",
    },
    {
      id: "apr_0002",
      contractorId: "con_0006",
      kind: "po-increase",
      reference: "CR-2026-121",
      description:
        "Increase PO-89012 by 140,000 to carry the programme manager through to go-live.",
      value: 140000,
      raisedOn: d(-9),
      requiredBy: d(6),
      state: "with-approver",
      currentApprover: "Finance Business Partner",
      currentApproverRole: "Finance",
      withApproverSince: d(-9),
      decidedOn: "",
      chases: [
        { date: d(-3), channel: "email", chasedWho: "Finance Business Partner", note: "PO at 77% and next invoice due shortly.", outcome: "Acknowledged, waiting on the delegation check." },
      ],
      notes:
        "Above the approval threshold, so needs the second signature. That is where these usually stall.",
    },
    {
      id: "apr_0003",
      contractorId: "con_0004",
      kind: "extension",
      reference: "CR-2026-124",
      description:
        "Six week extension to complete regression testing on release 3.",
      value: 34500,
      raisedOn: d(-4),
      requiredBy: d(0),
      state: "submitted",
      currentApprover: "Ben Osei",
      currentApproverRole: "Programme Director",
      withApproverSince: d(-4),
      decidedOn: "",
      chases: [],
      notes:
        "Decision needed today. The contract end date is already inside the notice period.",
    },
    {
      id: "apr_0004",
      contractorId: "con_0009",
      kind: "new-engagement",
      reference: "CR-2026-126",
      description:
        "New identity and access consultant, three days a week for six months.",
      value: 119808,
      raisedOn: d(-14),
      requiredBy: d(10),
      state: "with-approver",
      currentApprover: "Chief Information Security Officer",
      currentApproverRole: "CISO",
      withApproverSince: d(-14),
      decidedOn: "",
      chases: [
        { date: d(-8), channel: "email", chasedWho: "CISO office", note: "Asked whether the rate is accepted.", outcome: "Rate queried, benchmark comparison requested." },
        { date: d(-1), channel: "call", chasedWho: "CISO executive assistant", note: "Chased for a slot to discuss.", outcome: "Meeting offered next week, which is after the required-by date." },
      ],
      notes:
        "Rate sits below the benchmark, which is worth pointing out in the next chase.",
    },
    {
      id: "apr_0005",
      contractorId: "con_0007",
      kind: "new-engagement",
      reference: "CR-2026-119",
      description: "Data engineer for the data platform uplift, six months.",
      value: 233 * 1000,
      raisedOn: d(-30),
      requiredBy: d(-8),
      state: "approved",
      currentApprover: "",
      currentApproverRole: "",
      withApproverSince: d(-22),
      decidedOn: d(-8),
      chases: [
        { date: d(-16), channel: "email", chasedWho: "Sam Devlin", note: "Chased ahead of the start date.", outcome: "Approved two days later." },
      ],
      notes: "Approved, but the purchase order that follows it has still not been raised.",
    },
    {
      id: "apr_0006",
      contractorId: "con_0010",
      kind: "early-termination",
      reference: "CR-2026-115",
      description:
        "Confirm the engagement ends on the contracted date with no extension.",
      value: 0,
      raisedOn: d(-25),
      requiredBy: d(-6),
      state: "approved",
      currentApprover: "",
      currentApproverRole: "",
      withApproverSince: d(-20),
      decidedOn: d(-6),
      chases: [],
      notes: "Clean decision, taken in time for the notice period.",
    },
  ];

  const variations: Variation[] = [
    {
      id: "var_0001",
      contractorId: "con_0001",
      type: "extension",
      reference: "VAR-2025-041",
      effectiveFrom: d(-410),
      recordedOn: d(-425),
      previousEndDate: d(-410),
      newEndDate: d(-190),
      previousRate: 112,
      newRate: 112,
      previousHoursPerWeek: 40,
      newHoursPerWeek: 40,
      valueImpact: 98560,
      approvalId: null,
      notes: "First extension, rate held.",
    },
    {
      id: "var_0002",
      contractorId: "con_0001",
      type: "rate-change",
      reference: "VAR-2025-077",
      effectiveFrom: d(-190),
      recordedOn: d(-200),
      previousEndDate: d(-190),
      newEndDate: d(48),
      previousRate: 112,
      newRate: 118,
      previousHoursPerWeek: 40,
      newHoursPerWeek: 40,
      valueImpact: 112432,
      approvalId: null,
      notes:
        "Second extension with a rate increase of 5.4%. Agency cited market movement. Now sits above the benchmark.",
    },
    {
      id: "var_0003",
      contractorId: "con_0004",
      type: "extension",
      reference: "VAR-2026-012",
      effectiveFrom: d(-30),
      recordedOn: d(-38),
      previousEndDate: d(-30),
      newEndDate: d(15),
      previousRate: 1150,
      newRate: 1150,
      previousHoursPerWeek: 40,
      newHoursPerWeek: 40,
      valueImpact: 51750,
      approvalId: null,
      notes: "Extension to cover the delayed regression cycle.",
    },
    {
      id: "var_0004",
      contractorId: "con_0006",
      type: "extension",
      reference: "VAR-2026-008",
      effectiveFrom: d(-15),
      recordedOn: d(-26),
      previousEndDate: d(-15),
      newEndDate: d(96),
      previousRate: 1480,
      newRate: 1480,
      previousHoursPerWeek: 40,
      newHoursPerWeek: 40,
      valueImpact: 164280,
      approvalId: null,
      notes:
        "Extended to go-live. The PO was not increased at the same time, which is why it is now nearly exhausted.",
    },
    {
      id: "var_0005",
      contractorId: "con_0002",
      type: "hours-change",
      reference: "VAR-2026-019",
      effectiveFrom: d(-60),
      recordedOn: d(-66),
      previousEndDate: d(112),
      newEndDate: d(112),
      previousRate: 920,
      newRate: 920,
      previousHoursPerWeek: 40,
      newHoursPerWeek: 32,
      valueImpact: -33120,
      approvalId: null,
      notes: "Reduced to four days at the contractor's request. Cost came down accordingly.",
    },
    {
      id: "var_0006",
      contractorId: "con_0008",
      type: "extension",
      reference: "VAR-2025-088",
      effectiveFrom: d(-210),
      recordedOn: d(-220),
      previousEndDate: d(-210),
      newEndDate: d(-30),
      previousRate: 124,
      newRate: 124,
      previousHoursPerWeek: 40,
      newHoursPerWeek: 40,
      valueImpact: 89280,
      approvalId: null,
      notes: "Third and final extension.",
    },
  ];

  const invoices: Invoice[] = [
    // Overdue payment, agency chasing
    {
      id: "inv_0001",
      contractorId: "con_0006",
      vendorId: "ven_ravensbourne",
      invoiceNumber: "RVB-4471",
      poNumber: "PO-89012",
      periodStart: d(-75),
      periodEnd: d(-45),
      hoursClaimed: 168,
      amountExGst: 49840,
      receivedOn: d(-42),
      dueDate: d(-12),
      status: "approved",
      approver: "Ben Osei",
      sentForApprovalOn: d(-41),
      approvedOn: d(-33),
      paidOn: "",
      disputeReason: "",
      chases: [
        { date: d(-8), channel: "email", chasedWho: "Accounts Payable", note: "Approved a fortnight ago, still not paid.", outcome: "Said it is in the next payment run." },
        { date: d(-2), channel: "email", chasedWho: "Accounts Payable", note: "Missed the payment run, chased again.", outcome: "No response." },
      ],
      notes: "Ravensbourne have chased twice. This one is the reputational risk.",
    },
    // Sitting with an approver past SLA
    {
      id: "inv_0002",
      contractorId: "con_0001",
      vendorId: "ven_harbourline",
      invoiceNumber: "HBL-20881",
      poNumber: "PO-88213",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: 160,
      amountExGst: 18880,
      receivedOn: d(-13),
      dueDate: d(17),
      status: "with-approver",
      approver: "Rachel Lim",
      sentForApprovalOn: d(-12),
      approvedOn: "",
      paidOn: "",
      disputeReason: "",
      chases: [
        { date: d(-5), channel: "teams", chasedWho: "Rachel Lim", note: "Approval sitting nine days.", outcome: "Said she would do it Friday." },
      ],
      notes: "",
    },
    // Disputed
    {
      id: "inv_0003",
      contractorId: "con_0002",
      vendorId: "ven_kauri",
      invoiceNumber: "KDP-1192",
      poNumber: "PO-90114",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: 160,
      amountExGst: 23000,
      receivedOn: d(-12),
      dueDate: d(18),
      status: "disputed",
      approver: "Sam Devlin",
      sentForApprovalOn: d(-11),
      approvedOn: "",
      paidOn: "",
      disputeReason:
        "Billed at five days a week. The variation reducing her to four days took effect two months ago and the agency has not applied it.",
      chases: [
        { date: d(-7), channel: "email", chasedWho: "Sione Faleolo", note: "Sent the variation and asked for a credit note.", outcome: "Agreed to reissue, nothing received yet." },
      ],
      notes: "Do not approve until the credit note arrives.",
    },
    // Expected but not arrived
    {
      id: "inv_0004",
      contractorId: "con_0003",
      vendorId: "ven_northpoint",
      invoiceNumber: "",
      poNumber: "PO-90402",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: null,
      amountExGst: 21600,
      receivedOn: "",
      dueDate: "",
      status: "expected",
      approver: "",
      sentForApprovalOn: "",
      approvedOn: "",
      paidOn: "",
      disputeReason: "",
      chases: [],
      notes:
        "Period closed a fortnight ago and nothing has arrived. Accrual will be wrong if this is not chased.",
    },
    // Final invoice on an ended engagement, still not received
    {
      id: "inv_0005",
      contractorId: "con_0008",
      vendorId: "ven_harbourline",
      invoiceNumber: "",
      poNumber: "PO-87003",
      periodStart: d(-60),
      periodEnd: d(-30),
      hoursClaimed: null,
      amountExGst: 14880,
      receivedOn: "",
      dueDate: "",
      status: "expected",
      approver: "",
      sentForApprovalOn: "",
      approvedOn: "",
      paidOn: "",
      disputeReason: "",
      chases: [
        { date: d(-10), channel: "email", chasedWho: "Karen Whitfield", note: "Asked for the final invoice so the PO can be closed.", outcome: "Said it would come with the month end run." },
      ],
      notes: "Blocks closing PO-87003 and the offboarding checklist.",
    },
    // Clean paid history
    {
      id: "inv_0006",
      contractorId: "con_0001",
      vendorId: "ven_harbourline",
      invoiceNumber: "HBL-20744",
      poNumber: "PO-88213",
      periodStart: d(-75),
      periodEnd: d(-45),
      hoursClaimed: 168,
      amountExGst: 19824,
      receivedOn: d(-43),
      dueDate: d(-13),
      status: "paid",
      approver: "Rachel Lim",
      sentForApprovalOn: d(-42),
      approvedOn: d(-38),
      paidOn: d(-14),
      disputeReason: "",
      chases: [],
      notes: "",
    },
    {
      id: "inv_0007",
      contractorId: "con_0004",
      vendorId: null,
      invoiceNumber: "GT-2026-07",
      poNumber: "PO-89551",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: 168,
      amountExGst: 24150,
      receivedOn: d(-14),
      dueDate: d(16),
      status: "approved",
      approver: "Ben Osei",
      sentForApprovalOn: d(-13),
      approvedOn: d(-9),
      paidOn: "",
      disputeReason: "",
      chases: [],
      notes: "Direct engagement, self-billed monthly.",
    },
    {
      id: "inv_0008",
      contractorId: "con_0005",
      vendorId: "ven_harbourline",
      invoiceNumber: "HBL-20885",
      poNumber: "PO-90520",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: 80,
      amountExGst: 4960,
      receivedOn: d(-13),
      dueDate: d(17),
      status: "paid",
      approver: "Rachel Lim",
      sentForApprovalOn: d(-12),
      approvedOn: d(-10),
      paidOn: d(-3),
      disputeReason: "",
      chases: [],
      notes: "",
    },
    {
      id: "inv_0009",
      contractorId: "con_0010",
      vendorId: "ven_ravensbourne",
      invoiceNumber: "RVB-4488",
      poNumber: "PO-89740",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: 160,
      amountExGst: 19360,
      receivedOn: d(-11),
      dueDate: d(34),
      status: "with-approver",
      approver: "Ben Osei",
      sentForApprovalOn: d(-10),
      approvedOn: "",
      paidOn: "",
      disputeReason: "",
      chases: [],
      notes:
        "Last full invoice before the engagement ends. Watch the PO, only 14,000 of headroom left.",
    },
    {
      id: "inv_0010",
      contractorId: "con_0006",
      vendorId: "ven_ravensbourne",
      invoiceNumber: "RVB-4489",
      poNumber: "PO-89012",
      periodStart: d(-45),
      periodEnd: d(-15),
      hoursClaimed: 160,
      amountExGst: 47360,
      receivedOn: d(-10),
      dueDate: d(35),
      status: "on-hold",
      approver: "Ben Osei",
      sentForApprovalOn: d(-9),
      approvedOn: "",
      paidOn: "",
      disputeReason:
        "Would take PO-89012 past its value. Held until the PO increase under CR-2026-121 is approved.",
      chases: [
        { date: d(-4), channel: "email", chasedWho: "Finance Business Partner", note: "Explained the invoice is held behind the PO increase.", outcome: "Waiting on the delegation check." },
      ],
      notes: "This is the invoice that the stalled PO increase is actually blocking.",
    },
    {
      id: "inv_0011",
      contractorId: "con_0002",
      vendorId: "ven_kauri",
      invoiceNumber: "KDP-1178",
      poNumber: "PO-90114",
      periodStart: d(-75),
      periodEnd: d(-45),
      hoursClaimed: 128,
      amountExGst: 18400,
      receivedOn: d(-43),
      dueDate: d(-13),
      status: "paid",
      approver: "Sam Devlin",
      sentForApprovalOn: d(-42),
      approvedOn: d(-39),
      paidOn: d(-15),
      disputeReason: "",
      chases: [],
      notes: "",
    },
    {
      id: "inv_0012",
      contractorId: "con_0003",
      vendorId: "ven_northpoint",
      invoiceNumber: "NPR-8802",
      poNumber: "PO-90402",
      periodStart: d(-75),
      periodEnd: d(-45),
      hoursClaimed: 168,
      amountExGst: 22680,
      receivedOn: d(-44),
      dueDate: d(-23),
      status: "paid",
      approver: "Nadia Whare",
      sentForApprovalOn: d(-43),
      approvedOn: d(-40),
      paidOn: d(-24),
      disputeReason: "",
      chases: [],
      notes: "Twenty-one day terms, paid on time.",
    },
  ];

  return {
    version: 2,
    settings: { ...DEFAULT_SETTINGS },
    vendors,
    projects,
    rateCard,
    contractors,
    approvals,
    variations,
    invoices,
    comms: [
      {
        id: "com_0001",
        date: d(-6),
        channel: "email",
        direction: "outbound",
        contractorId: "con_0001",
        vendorId: "ven_harbourline",
        subject: "Extension intent - Mike Okafor",
        summary:
          "Advised Karen we are likely to extend by three months but the tenure review has to be completed first. Asked for a revised rate given the length of continuous engagement.",
        participants: "Karen Whitfield, Rachel Lim",
        followUpDate: d(3),
        topic: "Extension",
      },
      {
        id: "com_0002",
        date: d(-12),
        channel: "call",
        direction: "inbound",
        contractorId: "con_0003",
        vendorId: "ven_northpoint",
        subject: "Visa renewal timeline",
        summary:
          "Doug confirmed the visa renewal application is lodged and expects a decision inside six weeks. Asked us to hold the seat.",
        participants: "Doug McAllister",
        followUpDate: d(14),
        topic: "Compliance",
      },
      {
        id: "com_0003",
        date: d(-3),
        channel: "meeting",
        direction: "internal",
        contractorId: "con_0006",
        vendorId: "ven_ravensbourne",
        subject: "Programme resourcing checkpoint",
        summary:
          "Ben wants Helen through to go-live. Ravensbourne flagged a rate review at the next variation. Finance noted the PO is at 77% consumed and one invoice is already on hold behind it.",
        participants: "Ben Osei, Priya Nair, Finance Business Partner",
        followUpDate: d(4),
        topic: "Commercial",
      },
      {
        id: "com_0004",
        date: d(-1),
        channel: "email",
        direction: "outbound",
        contractorId: "con_0007",
        vendorId: "ven_kauri",
        subject: "Pre-start checklist - Tomas Silva",
        summary:
          "Chased Kauri for the completed background check and confirmed the start date. Flagged that no purchase order exists yet, so the first invoice will be held.",
        participants: "Sione Faleolo",
        followUpDate: d(4),
        topic: "Onboarding",
      },
      {
        id: "com_0005",
        date: d(-20),
        channel: "email",
        direction: "inbound",
        contractorId: null,
        vendorId: "ven_ravensbourne",
        subject: "MSA renewal",
        summary:
          "Priya raised that the master agreement lapses shortly and asked whether we intend to renew or retender.",
        participants: "Priya Nair, Procurement",
        followUpDate: d(2),
        topic: "Vendor management",
      },
      {
        id: "com_0006",
        date: d(-8),
        channel: "email",
        direction: "outbound",
        contractorId: "con_0002",
        vendorId: "ven_kauri",
        subject: "Incorrect billing - four day week not applied",
        summary:
          "Sent Kauri the variation reducing Aroha to four days and asked for a credit note against KDP-1192. They agreed to reissue.",
        participants: "Sione Faleolo, Accounts",
        followUpDate: d(1),
        topic: "Invoice dispute",
      },
    ],
    reminders: [
      {
        id: "rem_0001",
        type: "custom",
        title: "Build permanent conversion business case",
        detail:
          "Two long-tenure infrastructure contractors. Model the cost of converting versus extending and take it to the portfolio leadership meeting.",
        dueDate: d(21),
        contractorId: "con_0001",
        vendorId: null,
        status: "open",
        derived: false,
        owner: "Resource Manager",
      },
      {
        id: "rem_0002",
        type: "custom",
        title: "Monthly commitments and issues pack",
        detail:
          "Generate the reporting pack, add commentary on the two stalled approvals, and circulate before the portfolio meeting.",
        dueDate: d(9),
        contractorId: null,
        vendorId: null,
        status: "open",
        derived: false,
        owner: "Resource Manager",
      },
      {
        id: "rem_0003",
        type: "custom",
        title: "Propose a standard PO increase trigger",
        detail:
          "Two invoices have been held this quarter because the PO ran out before anyone noticed. Suggest a standing rule that a variation extending a contract must raise the PO at the same time.",
        dueDate: d(16),
        contractorId: null,
        vendorId: null,
        status: "open",
        derived: false,
        owner: "Resource Manager",
      },
    ],
    derivedState: {},
  };
}
